function LoadPhoto()
		{
			//drink
			document.getElementById("CA_PHE_1").src="images/CA_PHE_1.png";
			document.getElementById("CA_PHE_2").src="images/CA_PHE_2.png";
			document.getElementById("CA_PHE_3").src="images/CA_PHE_3.png";
			document.getElementById("CA_PHE_4").src="images/CA_PHE_4.png";
			document.getElementById("CA_PHE_5").src="images/CA_PHE_5.png";
			document.getElementById("CA_PHE_6").src="images/CA_PHE_6.png";
			document.getElementById("CA_PHE_7").src="images/CA_PHE_7.png";
			document.getElementById("CA_PHE_8").src="images/CA_PHE_8.png";
			document.getElementById("CA_PHE_9").src="images/CA_PHE_9.png";
			document.getElementById("CA_PHE_10").src="images/CA_PHE_10.png";
			document.getElementById("CA_PHE_11").src="images/CA_PHE_11.png";
			document.getElementById("CA_PHE_12").src="images/CA_PHE_12.png";
			document.getElementById("CA_PHE_13").src="images/CA_PHE_13.png";
			document.getElementById("CA_PHE_14").src="images/CA_PHE_14.png";
			document.getElementById("CA_PHE_15").src="images/CA_PHE_15.png";
			//eat
			document.getElementById("MON_AN_1").src="images/MON_AN_1.png";
			document.getElementById("MON_AN_2").src="images/MON_AN_2.png";
			document.getElementById("MON_AN_3").src="images/MON_AN_3.png";
			document.getElementById("MON_AN_4").src="images/MON_AN_4.png";
			document.getElementById("MON_AN_5").src="images/MON_AN_5.png";
			document.getElementById("MON_AN_6").src="images/MON_AN_6.png";
			document.getElementById("MON_AN_7").src="images/MON_AN_7.png";
			document.getElementById("MON_AN_8").src="images/MON_AN_8.png";
			document.getElementById("MON_AN_9").src="images/MON_AN_9.png";
			document.getElementById("MON_AN_10").src="images/MON_AN_10.png";
			document.getElementById("MON_AN_11").src="images/MON_AN_11.png";
			document.getElementById("MON_AN_12").src="images/MON_AN_12.png";
			document.getElementById("MON_AN_13").src="images/MON_AN_13.png";
			document.getElementById("MON_AN_14").src="images/MON_AN_14.png";
			document.getElementById("MON_AN_15").src="images/MON_AN_15.png";
		}